### ISSUE TITLE
Get Locale from Nextcloud, not from user

### ISSUE THREAD

**Issue by LeoColman** [cwilby/nextcloud-workflow-media-converter#101]
I believe that we are currently fetching User's Locale incorrectly.

It's not respecting user's language choice, but user's browser's choice (which most of the times is the same anyway).

On this repository, we're fetching the Locale from the user, and thus ignoring the right option. I'm not sure where this can be tho

**Comment by cwilby** [comment]
User language is stored in config.php, at least from what I understand so far.

* Set the [`default_language`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/language_configuration.html#default-language) key to `pt_BR` and your instance will fallback to `pt_BR` if the web browser does not provide a locale.

* Set the [`force_language`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/language_configuration.html#default-language) key to `pt_BR` and your instance will always use this language, regardless of user settings or browser language.

Each PHP class resolves a `IL10N` instance to perform translation, and Vue components use the global `t()` function to translate strings on the front-end.  Both of these methods rely on upstream functionality provided by NextCloud.

I wasn't able to find deviation from the NC standard for localization in this app, can you point to some code that I'm not seeing?

**Comment by cwilby** [comment]
I see now!  Thank you for pin-pointing.

I'll fix this with the next release, few other small issues to take care of here and there.

**Comment by cwilby** [comment]
Closing as I believe this is taken care of with #240, let me know if that's not the case.
