### ISSUE TITLE
Russian characters are not supported in pathnames and file names.

### ISSUE THREAD

**Issue by sosed213** [cwilby/nextcloud-workflow-media-converter#103]
Mounted shared folder with documents, photos and videos. Directory names in Russian.
The log says: No such file or directory.

**Comment by cwilby** [comment]
After looking, it may be an upstream issue in github.com/nextcloud/server

See 

https://github.com/nextcloud/server/issues/14981
https://github.com/nextcloud/server/issues/12318#issuecomment-437013889

Please tell me about your setup, and I'll try to dig in more.

**Comment by sosed213** [comment]
My details: Ubuntu Server 20.04, nginx, php8, postgresql
/etc/default/locale
LANG="ru_RU.UTF-8"

**Comment by cwilby** [comment]
This issue should now be resolved with #240
