### ISSUE TITLE
AV1 format?

### ISSUE THREAD

**Issue by Yajo** [cwilby/nextcloud-workflow-media-converter#117]
This is a feature request.

There's this new and fancy video codec AV1. [Details here](https://en.wikipedia.org/wiki/AV1).

It would be so nice if it were supported here!

BTW it also supports AVIF for images, which produces high quality images more compressed than webp. It would also be great, although it might be a separate request.

**Comment by cwilby** [comment]
Should be good to go!

https://github.com/cwilby/nextcloud-workflow-media-converter/commit/133b32fa702ca663c940b7b656935b56ad0761ed

You should ensure your ffmpeg binary was compiled with the AV1 encoder - https://trac.ffmpeg.org/wiki/Encode/AV1

**Comment by cwilby** [comment]
The Nextcloud app store has been inconsistent for me in the past:

It looks like the latest version was successfully released:
https://apps.nextcloud.com/apps/workflow_media_converter

Can you confirm you are on v1.2.13 or greater?  

(I'm attempting to update the app on my own Nextcloud instance but the screen is not loading)

<img width="952" alt="image" src="https://user-images.githubusercontent.com/13686317/140102046-65a23a75-6ad0-44c3-8f7f-19d1a52fad97.png">

**Comment by cwilby** [comment]
I forgot to bump the version number 🤦‍♂️ https://github.com/cwilby/nextcloud-workflow-media-converter/commit/9a0293066536788a8c2b10aa6c326bbb8638939f

v1.2.13 and v1.2.14 were never released, v1.2.20 should be released soon. https://github.com/cwilby/nextcloud-workflow-media-converter/actions/runs/1427342406

**Comment by Yajo** [comment]
Finally!

**Comment by cwilby** [comment]
"Finally"?  Gfy mate.

**Comment by cwilby** [comment]
So, so sorry I couldn't do that for you sooner. /s

**Comment by Yajo** [comment]
Hey friend, I see you seem to have some frustration about what I said, and I think that you probably misinterpreted my last comment. Or maybe I didn't express that fine because English is not my mother language. 😓 

I meant to express that I'm happy because this got fixed, and it was so fast! 🎉  I didn't mean that I'm bored of waiting, or that you're slow fixing bugs, or anything like that.

Thank you for fixing this so fast and for your help and work. 🙂

**Comment by cwilby** [comment]
Appreciate it - I apologize for the passive aggressive remarks - it's projection:

I once spent a summer with my dad in the office; the sysadmin spent half a day setting me up on a workstation, and I responded - "Finally, I've been waiting all day!" - followed by a rather stern word or two from the sysadmin 😬 It's stuck me with since, ergo projection.

Keep the ideas flowing @Yajo 🙂
