### ISSUE TITLE
add MXF format

### ISSUE THREAD

**Issue by rhz17** [cwilby/nextcloud-workflow-media-converter#135]
Feature request.

Yo, how are you?
There is a really cool format called MXF, it would be really interesting to have it in your project

[MXF information here](https://en.wikipedia.org/wiki/Material_Exchange_Format)

**Comment by cwilby** [comment]
Hi @rhz17 

I added your changes and released v1.2.21 which includes the MXF format.

I would have merged the PR but I had not added `js/` to .gitignore and want to keep the history clean-ish.

Thank you for your contribution 🚀

**Comment by rhz17** [comment]
Thank you so much, bro
