### ISSUE TITLE
Problem with system tag event

### ISSUE THREAD

**Issue by LucaRainone** [cwilby/nextcloud-workflow-media-converter#139]
## Steps to reproduce
1. Create a flow from Convert Media
2.  When Tag assigned
3. and File system tag is tagged with "some-tag"
4. Convert to format mp4 keep source file -> move output to specific folder (choose e folder) 
5. Go to a folder and tag a video with some-tag

### Expected behaviour
The convert media plugin should start

### Actual behaviour
```
This error happens: 

Argument 2 passed to OCA\WorkflowMediaConverter\Operation\ConvertMediaOperation::handleEvent() must be an instance of OCP\EventDispatcher\GenericEvent, instance of OCP\SystemTag\MapperEvent given, called in [...]workflow_media_converter/lib/Operation/ConvertMediaOperation.php on line 58
```
(note, this is the error in the system log after this patch (https://github.com/cwilby/nextcloud-workflow-media-converter/pull/138)).

otherwise is:
```
Error: Undefined property: TypeError::$getMessage at [...]workflow_media_converter/lib/Operation/ConvertMediaOperation.php#60
```

## Workflor Media Converter app
version 1.2.21

## Server configuration

**PHP version:** 7.3.31

**Nextcloud Version:** 22.2

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here

No errors have been found.
.
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** yes

### Server log (data/nextcloud.log)
<details>
```
Argument 2 passed to OCA\WorkflowMediaConverter\Operation\ConvertMediaOperation::handleEvent() must be an instance of OCP\EventDispatcher\GenericEvent, instance of OCP\SystemTag\MapperEvent given, called in [...]workflow_media_converter/lib/Operation/ConvertMediaOperation.php on line 58
```
</details>

**Comment by cwilby** [comment]
As a note - encryption is currently unsupported, need to look into decrypting/encrypting files during conversion.

**Comment by LucaRainone** [comment]
Yes, but it doesn't work also without encryption.

I tried to investigate the issue. I saw that the `GenericEvent` is deprecated and the `SystemTag\MapperEvent` extends only the Event class that does not have any useful method.

It gives us just some id and type (as strings). I don't know how nextcloud works and how we can fetch the node from these references.

**Comment by cwilby** [comment]
Ahh I see the issue now.  Thanks.

I looked around at other plugins.   They inject two variables in place of `GenericEvent`, a string named `$eventType` and  an `OCP\EventDispatcher\Event` object named `$event`.  If `$event` is a `GenericEvent`, the function returns early.  Otherwise, there is an edge case for renaming files, otherwise I guess it's assumed `getSubject()` exists.

In other words, this plugin should do what workflow_pdf_converter is doing [here](https://github.com/nextcloud/workflow_pdf_converter/blob/master/lib/Operation.php#L87-L92).

**Comment by LucaRainone** [comment]
I'm afraid not. Because the method `getSubject` not exists in `SystemTag\MapperEvent`. There should be a way to fetch the node instance (information about file) from `getObjectType(): string` and `getObjectId(): string ` instead.

I found this https://github.com/nextcloud/workflow_script/blob/master/lib/Operation.php#L144 that maybe help us!
There is an `elseif` block for  `MapperEvent`

**Comment by cwilby** [comment]
Cool!  It grabs the node id, instead of relying on "subject".  That works.  Will work that into this plugin soon (would also accept a PR - but, hakuna matata ¯\_(ツ)_/¯)

**Comment by LucaRainone** [comment]
I have no a dev environment for nextcloud. I tried all modifications on the live instance :D  I will try to give you an untested skelethon of modifications.

I have another problem that I don't understand. The plugin, after the modifications, does not throw any error but it doesn't convert anything. The source folder is an external storage folder: maybe it could be an edge case. But if I configure the plugin on file creation, it works as expected. So maybe the standard GenericEvent does something that MapperEvent doesn't.

When you will work on it, maybe you could test also with an external storage configuration (via GUI)

**Comment by cwilby** [comment]
For external storage, it _should_:

1.  Copy the file from external storage to the temp folder of the NextCloud instance.
2.  Run `ffmpeg` on the file in the temp folder.
3.  Move the converted file from the temp folder to external storage.

Hoping to support encryption if there is not some major constraint.

**Comment by skruehoetl** [comment]
The topic may be cold-ish, but I'd like to add my own part of the issue: 

I get the same error message with a very similar setup (docker, NC22.2.3, _PHP8.0.14_ (that's a difference), ffmpg installed via Dockerfile). However, I never had encryption enabled on this instance.

Does it make sense that I'm affected as well?

**Comment by whiskeytangofoxy** [comment]
Similar issue. NC23.0.1, php7.4, ffmpeg installed via apt on Ubuntu 20.04, docker-less installation, external NFS data storage. Getting this error:

`{"reqId":"A42YAHAFy2DARXxXNjVL","level":3,"time":"2022-02-23T19:00:52+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$convertMediaInParallel at /var/www/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#113","userAgent":"--","version":"23.0.1.2","exception":{"Exception":"Error","Message":"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$convertMediaInParallel at /var/www/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#113","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":113,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":42,"function":"lockConversion","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"62168fc49990a"}`

**Comment by cwilby** [comment]
@whiskeytangofoxy v1.3.3 should resolve that issue.

**Comment by whiskeytangofoxy** [comment]
> @whiskeytangofoxy v1.3.3 should resolve that issue.

So it did. Thank you!

**Comment by cwilby** [comment]
@LucaRainone Closing as a number of issues (including this point) point to: #https://github.com/cwilby/nextcloud-workflow-media-converter/issues/264
