### ISSUE TITLE
Cannot excute ffmpeg flow (.mov -> .mp4) when installed on Docker container

### ISSUE THREAD

**Issue by tecandrew** [cwilby/nextcloud-workflow-media-converter#146]
## Steps to reproduce
1. Add `app` to nextcloud instance
2. Add flow instructions to convert `.mov` ->`.mp4`
3. Take live photo on iphone (auto adds `.jpg` and `.mov`)
4. See nextcloud logs

![image](https://user-images.githubusercontent.com/21319730/143940070-63db48c3-2efc-4afb-9cb7-bc662376841b.png)

### Expected behaviour
Convert `.mov` to `.mp4`

### Actual behaviour
Logs show that `ffmpeg` cannot execute. `ffmpeg` can be executed by itself when `-it`'ing into the docker container instance. the `.mov` file itself could also be converted when individually executed from the web interface.

## Server configuration

**Operating system**:  Ubuntu (docker image `nextcloud:production`)

**Web server:** Apache + Nginx

**Database:**  Maria 

**PHP version:**
```
lafcadio@nuc:~/nextcloud$ sudo docker-compose exec --user www-data app php --version
PHP 8.0.13 (cli) (built: Nov 19 2021 21:36:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies
```

**Nextcloud Version:**  22.2.3.0

**Where did you install Nextcloud from:** Docker

**Signing status:** 

```
`No errors have been found.`
```

**List of activated apps:**

<details>

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - audioplayer: 3.2.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.4.0
  - camerarawpreviews: 0.7.15
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - drawio: 1.0.1
  - duplicatefinder: 0.0.13
  - external: 3.9.0
  - extract: 1.3.2
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - flow_notifications: 1.2.0
  - imageconverter: 1.3.2
  - integration_github: 1.0.2
  - integration_gitlab: 1.0.3
  - integration_twitter: 1.0.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - maps: 0.1.9
  - metadata: 0.14.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.2.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - previewgenerator: 3.2.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - radio: 1.0.3
  - ransomware_protection: 1.11.0
  - recognize: 1.6.10
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - video_converter: 1.0.3
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_media_converter: 1.2.23
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - circles
  - electronicsignatures
  - encryption
  - federation
  - files_external
  - mail
  - richdocuments
  - richdocumentscode
  - spreed
  - support
  - user_ldap
```

</details>

**Nextcloud configuration:**

<details>

```
lafcadio@nuc:~/nextcloud$ docker-compose exec --user www-data app php occ config:list system
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.enjoi.dev"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "http:\/\/cloud.enjoi.dev\/",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "app_install_overwrite": [
            "radio"
        ]
    }
}
```

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Server log (data/nextcloud.log)
<details>

```
[Symfony\Component\Process\Exception\ProcessFailedException] :: (0) :: The command "ffmpeg -threads 2 -i /tmp/oc_tmp_spXnVa-.mov /tmp/oc_tmp_spXnVa-.mp4" failed. Exit Code: 127(Command not found) Working directory: /var/www Output: ================ Error Output: ================ sh: 1: ffmpeg: not found :: #0 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(36): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->convertMedia() #1 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->run(Array) #2 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #3 /var/www/html/cron.php(127): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #4 {main}
```

</details>

**Comment by cwilby** [comment]
Thank you for the thorough report, I'll look into this next.

Might not be related, but do you have a Dockerfile that extends `nextcloud:production` and runs `apt install ffmpeg`, or do you use `nextcloud:production` directly, then install ffmpeg via shell?

**Comment by tecandrew** [comment]
Thanks @cwilby. Yes, I have a Dockerfile that extends `nextcloud:production`.  

```
FROM nextcloud:production

# imagemagick + ffmpeg
RUN apt update && apt install -y libmagickcore-6.q16-6-extra ffmpeg imagemagick ghostscript
```

Going into the instance gets me the following:

```
lafcadio@nuc:~/nextcloud$ sudo docker-compose exec --user www-data app bash
www-data@a6ceb3a6a3f9:~/html$ ffmpeg -version
ffmpeg version 4.3.3-0+deb11u1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

**Comment by mason-xx** [comment]
experiencing the same with an alpine image... after installing ffmpeg with apk i recieve a similar error:

`[Symfony\Component\Process\Exception\ProcessFailedException] :: (0) :: The command "ffmpeg -threads 0 -i /tmp/oc_tmp_GEiGDn-.mov /tmp/oc_tmp_GEiGDn-.mp4" failed. Exit Code: 127(Command not found) Working directory: /home/www-data Output: ================ Error Output: ================ sh: ffmpeg: not found :: #0 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(43): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->convertMedia() #1 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->run(Array) #2 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #3 /var/www/html/cron.php(128): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #4 {main}`

**Comment by Gymnae** [comment]
I think this is also my issue, I am running an image extending the official docker image with ffmpeg

**Comment by Gymnae** [comment]
To add, this app: https://github.com/PaulLereverend/NextcloudVideo_Converter works fine in my docker setup, it also uses ffmpeg. I can't code, but maybe the way they implemented calling ffmpeg could also work for this app, @cwilby

**Comment by eraser2021999** [comment]
I have the same issue:
`Nextcloud 25.0.1`
`ffmpeg version 4.3.5-0+deb11u1 Copyright (c) 2000-2022 the FFmpeg developers`

Docker container, `nextcloud:full` extending the `latest` image. 

I believe this issue relates to user rights, but I can't validate with certainty.

**Comment by eraser2021999** [comment]
It seems that worflow creates the ffmpeg conversion process via PHP function `proc_open` and not by calling `exec` as I believed initially. When executed with `exec` it correctly starts the conversion process, but in case of `proc_open` we have the following situation:
`ffmpeg version 4.3.5-0+deb11u1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
/tmp/oc_tmp_cXa42h-.mov: No such file or directory`

Notice the error is in fact **/tmp/oc_tmp_cXa42h-.mov: No such file or directory**, I believe the issue is not related to permission regarding `ffmpeg` executable, but with the media files.

**Comment by eraser2021999** [comment]
After spending some time on the issue, it seemed that the culprit was the `ProcessFactory.php`, more specifically `return new Process($command, null, null, null, null);`
It seems there is a change in Symphony 4.2 (or I might be wrong), but long story short, I replaced `return new Process($command, null, null, null, null);` with `return Process::fromShellCommandline($command);` and that seems to fix batch processing. 

However, a new error appears:
`[Symfony\Component\Process\Exception\ProcessTimedOutException] :: (0) :: The process "ffmpeg -threads 0 -i /tmp/oc_tmp_8naY8l-.mov /tmp/oc_tmp_8naY8l-.mp4" exceeded the timeout of 60 seconds. :: #0 /var/www/html/custom_apps/maps/vendor/symfony/process/Process.php(430): Symfony\Component\Process\Process->checkTimeout() #1 /var/www/html/custom_apps/maps/vendor/symfony/process/Process.php(254): Symfony\Component\Process\Process->wait() #2 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(142): Symfony\Component\Process\Process->run() #3 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(44): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->convertMedia() #4 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->run(Array) #5 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(58): OCP\BackgroundJob\Job->start(Object(OC\BackgroundJob\JobList)) #6 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(48): OCP\BackgroundJob\QueuedJob->start(Object(OC\BackgroundJob\JobList)) #7 /var/www/html/cron.php(152): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #8 {main}`

**Comment by cwilby** [comment]
https://github.com/cwilby/nextcloud-workflow-media-converter/releases/tag/v1.6.6

Thank you @eraser2021999 🎉

**Comment by Gymnae** [comment]
Is it just me or is the new release not yet in the App Store?

**Comment by cwilby** [comment]
@Gymnae Habit from work, assumed the release auto-updated the release numbers in source code.

Just released 1.7.0, that should make it's way to the stores soon (It can take a few hours, no visibility into that process)

**Comment by mason-xx** [comment]
hmm I still got the same error with 1.70...

{"reqId":"FW6YcOeuYXTobKGTZhHK","level":3,"time":"2022-11-26T20:35:09+00:00","remoteAddr":"","user":"--","app":"workflow_media_converter","method":"","url":"--","message":"[Symfony\\Component\\Process\\Exception\\ProcessFailedException] :: (0) :: The command \"ffmpeg -threads 0 -i /tmp/oc_tmp_gaIOfA-.mov /tmp/oc_tmp_gaIOfA-.mkv\" failed.\n\nExit Code: 127(Command not found)\n\nWorking directory: /home/www-data\n\nOutput:\n================\n\n\nError Output:\n================\nsh: ffmpeg: not found\n :: #0 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(44): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->convertMedia()\n#1 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->run(Array)\n#2 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(58): OCP\\BackgroundJob\\Job->start(Object(OC\\BackgroundJob\\JobList))\n#3 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(48): OCP\\BackgroundJob\\QueuedJob->start(Object(OC\\BackgroundJob\\JobList))\n#4 /var/www/html/cron.php(152): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#5 {main}","userAgent":"--","version":"25.0.1.1","data":{"app":"workflow_media_converter"}}

**Comment by mason-xx** [comment]
this seems to work, a 

`docker-compose exec app ffmpeg -version`

shows 
```

ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
configuration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100

```

**Comment by eraser2021999** [comment]
> docker-compose exec app ffmpeg -version

it should be like this: `docker-compose exec app --user www-data ffmpeg -version`. Running by default it will be executed as root which doesn't help in this case.

**Comment by mason-xx** [comment]
yeah i noticed my error and edited my comment... works with the www-data user

**Comment by abhilesh** [comment]
I am facing the same issue with Nextcloud v28.0.3 and Automated media conversion v1.9.3. I have `ffmpeg` v5.1.4 installed - 
```
[Symfony\Component\Process\Exception\ProcessFailedException] :: (0) :: The command "ffmpeg -threads 0 -i /tmp/oc_tmp_vw4VF6-.avi /tmp/oc_tmp_vw4VF6-.mp4" failed. Exit Code: 127(Command not found) Working directory: /var/www Output: ================ Error Output: ================ sh: 1: ffmpeg: not found :: #0 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(65): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->convertMedia() #1 /var/www/html/lib/public/BackgroundJob/Job.php(81): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->run(Array) #2 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(57): OCP\BackgroundJob\Job->start(Object(OC\BackgroundJob\JobList)) #3 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\QueuedJob->start(Object(OC\BackgroundJob\JobList)) #4 /var/www/html/cron.php(152): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #5 {main}
```

**Comment by abhilesh** [comment]
> I am facing the same issue with Nextcloud v28.0.3 and Automated media conversion v1.9.3. I have `ffmpeg` v5.1.4 installed -
> 
> ```
> [workflow_media_converter] Error: [Symfony\Component\Process\Exception\ProcessFailedException] :: (0) :: The command "ffmpeg -threads 0  -i /tmp/oc_tmp_vw4VF6-.avi /tmp/oc_tmp_vw4VF6-.mp4" failed.
> 
> Exit Code: 127(Command not found)
> 
> Working directory: /var/www
> 
> Output:
> ================
> 
> 
> Error Output:
> ================
> sh: 1: ffmpeg: not found
>  :: #0 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(65): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->convertMedia()
> #1 /var/www/html/lib/public/BackgroundJob/Job.php(81): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->run(Array)
> #2 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(57): OCP\BackgroundJob\Job->start(Object(OC\BackgroundJob\JobList))
> #3 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\QueuedJob->start(Object(OC\BackgroundJob\JobList))
> #4 /var/www/html/cron.php(152): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
> #5 {main}
> 	from ? by -- at Mar 9, 2024, 3:55:02 PM
> ```

**SOLVED** - 
I am running a separate `cron` container in my `docker-compose` stack to be used with nextcloud. While I had correctly installed `ffmpeg` in the nextcloud container, the workflow was actually being run inside the `cron` container which did not have `ffmpeg` installed hence leading to the `ffmpeg not found` error.

Fixed it by installing `ffmpeg` in the `cron` container and for persistent changes building the docker image for `cron` with `ffmpeg` installed.
