### ISSUE TITLE
Suggestion : textarea override FFMPEG parameters per tasks

### ISSUE THREAD

**Issue by ES-Six** [cwilby/nextcloud-workflow-media-converter#179]
I create this issue to suggest an improvement :
- Allow users to override / add specific FFMPEG arguments

Exemple : this could be a simple and optional textarea inside the interface like this :
![image](https://user-images.githubusercontent.com/13310075/152060975-1aa63407-8b94-46b5-9a41-fd62c3bfb346.png)

This can be done in combination with the following issue if needed : https://github.com/cwilby/nextcloud-workflow-media-converter/issues/30

This kind of functionnalities can be found in other conversion softwares acting as FFMPEG GUI as it's a way to provide a lot of functionnalities to advanced users with a minimum of changes in the interface.

This can allow users to accomplish the following use cases : 
- Preserve ID3 (or other metadata format) tags (on audio and other files)
- Control compression factor depending on the codec used
- Enable advanced users to use advanced FFMPEG functionalities (like resizing, etc.)

I also have an additional question :
Is there a way to speedup the tasks queue ? Because it take at least 5 to 10 minutes to start a task.

Thank you for reading.

**Comment by cwilby** [comment]
Great work, this is a lot simpler. (Open to PRs if I don't get to it first 👍)

For processing speed, that's determined by the scheduling type you have in Settings > Basic Settings
![image](https://user-images.githubusercontent.com/13686317/152217011-89b11c5e-173a-4ca2-aeb2-e3cfd3d5e99d.png)

You could try setting this to Webcron and have a separate process call Webcron every minute via HTTP.

Other than that, the 5/10 minute wait is due to how Nextcloud background jobs are currently built.

**Comment by ES-Six** [comment]
If I understand well, webcron is the beast approach as we can trigger the nextcloud cron by calling it's URL as mentioned in the nextcloud doc : https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#webcron


So, concerning the queue approach, I have a suggestion (a little bit hacky) but it could solve the delay between task is added to queue and started.

It can be represented as an option in the module options like this :
![image](https://user-images.githubusercontent.com/13310075/152228846-86fad29f-b7a0-4745-859a-9b06e2a13078.png)

This option could do the following :
- When a job is added to a queue, the module calls the webcron URL of the netxcloud instance (with curl or other stuff)
    - That will trigger jobs to start
- When a job finish, the module calls the webcron URL
    - That will trigger the next tasks if there is at least one remaining

**Comment by cwilby** [comment]
Just swinging through to say I still like the idea, it's coming soon.

**Comment by chriskloe** [comment]
Is there a time frame since when it will be available?

**Comment by cwilby** [comment]
With the recent fixes to support NC26 I should be able to get to this next - maybe 1-2 weeks.

**Comment by mv-debug** [comment]
Does this solution also include the possibility to add parameters to the flow task?

I have got the issue of "Too many packets buffered for output stream 0:0." And I need the parameter *-max_muxing_queue_size 1024* for a successful conversation.

**Comment by cwilby** [comment]
@mv-debug Yes - you'll be able to add `-max_muxing_queue_size 1024` to a textbox, and that will be parsed and passed to ffmpeg.

**Comment by cwilby** [comment]
Hey @ES-Six @mv-debug @chriskloe,

This is now available in v1.9.0 for flows and batches:

<img width="847" alt="image" src="https://github.com/cwilby/nextcloud-workflow-media-converter/assets/13686317/c81af2eb-cdd2-4391-b495-5e2464242e53">
