### ISSUE TITLE
No support for .mkv file

### ISSUE THREAD

**Issue by codereptile** [cwilby/nextcloud-workflow-media-converter#196]
I have noticed that even though mkv is supported by ffmpeg, there is simply no option to select such a format. Most likely this could be solved simply by creating such an option.

**Comment by cwilby** [comment]
Piece of cake 🎂

https://github.com/cwilby/nextcloud-workflow-media-converter/commit/609fdfc676b24e6623e71297ed6ab76dfda5c7a5

MKV should be available in v1.3.4
