### ISSUE TITLE
Request to update documentation.

### ISSUE THREAD

**Issue by codereptile** [cwilby/nextcloud-workflow-media-converter#200]
Please add that it is **required** to have cron service as background jobs handler. I didn't notice, that means others might run into the same problem. 

Also, please add that there might be a 5 minute (or else, depending on the config of cron) delay.

**Comment by cwilby** [comment]
Will do.

Was some other cron type selected and it was causing issues?  Or, was no cron type selected so nothing worked?

**Comment by GregorKopka** [comment]
Without looking at it specifically, so only an educated guess: Could webcron run into a webserver script execution timeout?

**Comment by codereptile** [comment]
@cwilby, guess later is better than never - the issue was that nextcloud by default uses AJAX instead of cron, so the answer would be that no cron type was selected.

**Comment by codereptile** [comment]
@GregorKopka could you please elaborate?

**Comment by cwilby** [comment]
@GregorKopka  Yes, the webserver script could timeout, given your configuration.  (Apache or nginx/php-fpm, for example)

**Comment by cwilby** [comment]
Documentation has been updated with a note about the potential lead time for conversion to start.
