### ISSUE TITLE
Bluray iso

### ISSUE THREAD

**Issue by ltheakston** [cwilby/nextcloud-workflow-media-converter#203]
This is a feature request.

I have a few bluray iso files and would love to convert them, and any new ones, to a format such as mkv or avi.

Would it be possible to add support for iso files?

**Comment by cwilby** [comment]
Thank you for the feature request.  

Closing as this would be out of scope for this project.  

I suggest you setup some other automation process to extract the contents of the ISO image, and then setup a conversion rule in this project to convert those contents into another format such as mkv or avi.
