### ISSUE TITLE
Internal Server Error when trying to reach (any) settings

### ISSUE THREAD

**Issue by MadMakz** [cwilby/nextcloud-workflow-media-converter#21]
## Steps to reproduce
1. Install Automated media conversion
2. Go to <nc url>/settings/user or <nc url>/settings/admin/workflow

### Expected behaviour
No errors.

### Actual behaviour
* Internal Server Error:
![Automated Media Conversion](https://user-images.githubusercontent.com/3930214/124400413-71a1fc80-dd22-11eb-88ff-122bc9314184.jpg)

* No logs (empty nextcloud.log)

#### Versions
* Nextcloud: 21.0.3
* Automated media conversion: 1.2.8
* PHP-FPM 7.3.29
* nginx 1.14.2

### Apps
**(_Automated media conversion_ app has been disabled)**

**Enabled:**
  - accessibility: 1.7.0
  - activity: 2.14.3
  - audioplayer: 3.1.0
  - audioplayer_editor: 0.3.0
  - camerarawpreviews: 0.7.11
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - encryption: 2.9.0
  - external: 3.8.2
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - impersonate: 1.8.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - metadata: 0.13.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - previewgenerator: 3.1.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - support: 1.4.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - workflowengine: 2.3.0

**Disabled:**
  - admin_audit
  - announcementcenter
  - bruteforcesettings
  - checksum
  - dashboard
  - firstrunwizard
  - ocdownloader
  - printer
  - recommendations
  - sharebymail
  - survey_client
  - user_ldap
  - video_converter
  - w2g2
  - weather_status
  - workflow_media_converter

**Comment by cwilby** [comment]
@MadMakz You have encryption enabled, which is something the app does not currently support.

My understanding currently is that apps don't have a way to decrypt encrypted files using the NC framework, as "encryption" is itself an app, not a function available in the core framework which is available to all apps.

It's something I'm planning to look into as it should be possible to decrypt files prior to conversion and encrypt the output.  The trick is accessing the key.  Either I can find a way to access the key, or ask users to provide it in admin settings.

This is optional but helps to confirm that encryption is the issue - if you disable encryption, does this error message go away?

**Comment by MadMakz** [comment]
Sorry, had loglevel 4, with 2 i get

`[index] Error: Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at <<closure>>

0. /var/www/vhosts/my.nextcloud/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "index")
1. /var/www/vhosts/my.nextcloud/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "index", OC\AppFramework\ ... {}, {section: "perso ... "})
2. /var/www/vhosts/my.nextcloud/lib/base.php line 993
   OC\Route\Router->match("/settings/user")
3. /var/www/vhosts/my.nextcloud/index.php line 37
   OC::handleRequest()

GET /settings/user`

**Comment by MadMakz** [comment]
Just disabled encryption. Error is still there

I however had at one point encryption enabled but i switched back to unencrypted some time ago.

**Comment by cwilby** [comment]
I'll look at this tomorrow as I'm headed out shortly for fireworks and tacos.

It seems I'm missing some glue code as I don't see `OCA\WorkflowMediaConverter` in the error stack.

Can you try to get an expanded version of that log entry by opening `data/nextcloud.log` by hand and pasting the entry here?

**Comment by MadMakz** [comment]
Yeah, weird way of "formatted export" feature from nextcloud.

Here's the more raw thing from .log
[ncise.txt](https://github.com/cwilby/nextcloud-workflow-media-converter/files/6760684/ncise.txt)

Happy 4th of july there overseas :D

**Comment by cwilby** [comment]
Ahhh I used some php 7.4 syntax, know what needs to be fixed now.

**Comment by cwilby** [comment]
Version 1.2.9 has been deployed to the app store with support for PHP 7.3 👍

**Comment by MadMakz** [comment]
Thank you for the quick solution :)

Just one thing: 

> 
> 
> Version 1.2.9 has been deployed to the app store with support for PHP 7.3 👍

```
<dependencies>
        <php min-version="7.4" 
```

**Comment by cwilby** [comment]
Version 1.2.10 on the way out with that change
