### ISSUE TITLE
Possibility to reduce quality

### ISSUE THREAD

**Issue by jakobroehrl** [cwilby/nextcloud-workflow-media-converter#22]
It would be nice if the script could reduce video quality to save storage.
This could be solved if the user could add some ffmpeg optins

**Comment by defilor** [comment]
Same. Looking for a way to automatically compress videos that were screen-captured without much compression. Would like them to stay the same format, right now I can't find a way to make it process a file and just apply a different compression level. More ffmpeg options would be much appreciated.

**Comment by cwilby** [comment]
In an older prototype I had some options for this:

![image](https://user-images.githubusercontent.com/13686317/130290814-117d51e7-68bc-4acd-919a-e8fe3b5dc471.png)

It was a big effort at the time for the initial release, but something I'll look into adding to both the Flow editor and back-conversion.

**Comment by dmgeurts** [comment]
Same for audio files, it's helpful to be able to downsample hifi quality to speech.

**Comment by jakobroehrl** [comment]
Hi @cwilby,
could you maybe look over this? It would be super helpful to me, If I could reduce the quality of my big videos. 
A 
`ffmpeg -i bigInputFileFromSmartphoe.mp4 smallOutputFileForStorage.mp4`
would be wonderful

**Comment by cwilby** [comment]
Closing in favor of https://github.com/cwilby/nextcloud-workflow-media-converter/issues/179
