### ISSUE TITLE
l10n: Context needed for string "source files"

### ISSUE THREAD

**Issue by fantonialice** [cwilby/nextcloud-workflow-media-converter#249]
https://github.com/cwilby/nextcloud-workflow-media-converter/blob/5ebb2e468cbbda32f4e2ba7050dc48512f304326/src/components/CreateConversionBatch.vue#L23
Please enlight us.
Reported at Transifex. Please see https://www.transifex.com/nextcloud/nextcloud/translate/#pt_BR/workflow_media_converter/439962391.

**Comment by cwilby** [comment]
Hi @fantonialice 

I am getting a 404 error when visiting that link.  

Another way of expressing this is "Find source files in this format".

**Comment by fantonialice** [comment]
Weird, that link works for me.

Context is needed regarding "source file". Could you enlighten me, please?
