### ISSUE TITLE
Add failed conversion log

### ISSUE THREAD

**Issue by cwilby** [cwilby/nextcloud-workflow-media-converter#25]
Need to add:

- [ ] Failed conversions component: a scrolling list of failed conversions
- [ ] Admin settings: embed failed conversions into an `overflow: auto` container
- [ ] Personal settings: add modal with failed conversions list per conversion batch

**Comment by Yajo** [comment]
Today I got a failed batch. All I have is this screen:

![imagen](https://user-images.githubusercontent.com/973709/146581625-3e528a7e-9cb9-45b6-be6d-37225153c7b0.png)

Is there some way to get logs?

**Comment by cwilby** [comment]
Change `/var/www/html/config/config.php` to include

```php
[
    'loglevel' => 1
]
```

And you will see when jobs start/stop etc.
