### ISSUE TITLE
Error when attempting to convert batch files

### ISSUE THREAD

**Issue by 2000gtacoma** [cwilby/nextcloud-workflow-media-converter#259]
## Steps to reproduce
1. Create a test folder in nextcloud
2. Drop an avi video into the folder
3. Create a conversion batch under the media conversion

### Expected behaviour
1. Conversion should search the folder(s), find the files that need to be converted and convert them. 
2. Work flows appear not to pickup new files as they are dropped in and convert them.

### Actual behaviour
Batch conversion shows queued. Then moves to converting. Appears to hang at converting until an error is reported in nextcloud logs. Error below. After the error is issued, usually the conversion job moves forward and converts without issue. I did look at some of the other issues/comments and enable parallel media conversion is enabled. Thread slider is set to 0 to show all issues

Error	PHP	Error: Undefined array key "convertMediaInParallel" at /config/www/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81
/config/www/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php - line 81:

OC\Log\ErrorHandler::onError()

/config/www/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php - line 42:

OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->parseArguments()

/config/www/nextcloud/lib/public/BackgroundJob/Job.php - line 79:

OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->run()

/config/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php - line 47:

OCP\BackgroundJob\Job->execute()

/config/www/nextcloud/cron.php - line 151:

OCP\BackgroundJob\QueuedJob->execute()

## Workflow Media Converter app
1.6.2

**Workflow Media Converter app version:** (see apps admin page: `/index.php/settings/apps`)
1.6.2

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Alpine

**Web server:**
Nginx

**Database:** 
Maria

**PHP version:**
8.0.25

**Nextcloud Version:** (see admin page)
24.0.6

**Where did you install Nextcloud from:**
Docker

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
 "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.23:444",
            "mydomain.org"
        ],
        "dbtype": "mysql",
        "version": "24.0.6.1",
        "overwrite.cli.url": "https:\/\/mydomain.org",
        "overwritehost": "mydomain.org",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
No

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by cwilby** [comment]
Hey @2000gtacoma 

Version 1.6.4 should resolve these issues, see #252 for more details or wait for that version to make it's way to the app store.

**Comment by cwilby** [comment]
Also, be sure to try checking "Enable Parallel Media Conversion" under administration settings.

I implemented a locking mechanism for when that box is unchecked.   It is not really working as I intended and will likely be removed, just thought you might want to know.
