### ISSUE TITLE
[Bug] Media conversion deletes metadata for .mov files

### ISSUE THREAD

**Issue by gymnae** [cwilby/nextcloud-workflow-media-converter#274]
## Steps to reproduce
1. Upload a .mov file 
2. Have a flow pickup the file and transcode/encode it to .mp4
3. Notice that the meta data such as date and time of recording become erased

### Expected behaviour
Retain all metadata as part of the original

### Actual behaviour
At least the metadata connected to data and time of recording are deleted, maybe more

## Workflow Media Converter app

**Workflow Media Converter app version:** 
1.7.0

## Server configuration

**Operating system**: 
Debian 11, official and extended docker image

**Web server:** 
php-fpm & caddy

**Database:**
PostgreSQL

**PHP version:** 
8.1

**Nextcloud Version:**
25.0.1

**Where did you install Nextcloud from:**
offiical, extended docker status

**Signing status:**
all good

**Comment by Gymnae** [comment]
#179 could fix this, if ffmpeg options allow for retaining also video metadata,
Or per default, set these flags:
`-movflags use_metadata_tags -map_metadata 0`
Credit: https://video.stackexchange.com/questions/23741/how-to-prevent-ffmpeg-from-dropping-metadata

**Comment by Gymnae** [comment]
Not usually the one to bump, but this bug create manual fixup, since I have to recreate metadata after conversion, @cwilby

**Comment by cwilby** [comment]
@Gymnae Appreciate the bump, I've prioritized this for the next release.

**Comment by cwilby** [comment]
@gymnae Coming back to this, you can now pass options to ffmpeg as shown below:

![image](https://github.com/cwilby/nextcloud-workflow-media-converter/assets/13686317/65a3d2d4-b100-401c-add8-d85b5fadc7bd)

Add `-movflags use_metadata_tags -map_metadata 0` to "Output flags" should take care of this issue.

Closing, but let me know if that doesn't fix it.
