### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by SadBoen** [cwilby/nextcloud-workflow-media-converter#277]
## Steps to reproduce
1. Install nextcloud in truenas scale by truechart script.
2. Install App in nextcloud app store
3. converter a h.264 mp4 file to .....mov / av1(I just try these)

### Expected behaviour
(错误代码 0) OCA\WorkflowMediaConverter\BackgroundJobs\BatchConvertMediaJob::findUnconvertedMediaInFolder(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/BatchConvertMediaJob.php on line 42 

Hope this cloud be fixed, or how to use this app correctly, thank you very much!

**Comment by cwilby** [comment]
Hey @SadBoen, I released v1.8.4 to Nextcloud yesterday that fixes this issue - give it another try 👍
