### ISSUE TITLE
Add FFmpeg options per codec

### ISSUE THREAD

**Issue by cwilby** [cwilby/nextcloud-workflow-media-converter#30]
For each codec in `./src/constants/formats.js`, add a schema to configure parameters passed to FFmpeg.

**Comment by dmgeurts** [comment]
This would be great, as I'm currently setting this app up to convert an m4a to mp3 but I'd like to reduce the quality settings as it's speech and not music.

**Comment by eibex** [comment]
It would be great keep the same file format but only change codecs as well (e.g. *.mp4 HEVC to *.mp4 H264)

**Comment by cwilby** [comment]
As a note - this is something I wanted while building, but decided against it when it met my needs and I could move on.

Configuration options vary on the input format and output format.  There needs to be a set of "input" configuration options, and "output" configuration options, for every codec in the list of supported formats that may grow.

In an earlier version of this project there was the following Vue code that shows/hides configuration options if they exist, or displays a message asking users to contribute these settings.

Old project: https://github.com/cwilby/nextcloud-automatic-media-encoder/blob/master/src/components/ConversionRule.vue#L41-L63

```vue
<template>
...
<div class="automc-conversion-rule__encoder-settings">
    <label>With these encoder settings</label>
    <div class="automc-conversion-rule__encoder-settings-body">
        <div v-if="toFormat">
            <div v-if="toFormat.settings_schema">
                {{ toFormat }} Settings
            </div>
            <div v-else>
                <p>The "{{ toFormat.label }}" format has no supported encoder settings.</p>
                <small>While you may still convert to this format, default parameters will be used which may result in media that is higher/lower in quality than desired.</small>
                <small>
                    Found an issue or want to contribute settings for this encoder?
                    <a target="_blank" rel="noopener noreferrer" :href="`https://github.com/cwilby/nextcloud-automatic-media-encoder/issues/new?title=[Encoder Settings Request] ${toFormat.label}`">
                        <span>Open an issue on GitHub</span>
                    </a>
                </small>
            </div>
        </div>
        <div v-else>
            (Select a "To" format to see encoder settings)
        </div>
    </div>
</div>
...
</template>
```

This needs to make its way into this project.

**Comment by TychoWerner** [comment]
Any updates on this?

**Comment by cwilby** [comment]
Closing in favor of https://github.com/cwilby/nextcloud-workflow-media-converter/issues/179
