### ISSUE TITLE
Missing audio in output

### ISSUE THREAD

**Issue by chriskloe** [cwilby/nextcloud-workflow-media-converter#323]
I am trying to convert my video archive with this plugin. At the moment I tried to convert mkv files to hvec and h.264. None of the outputs seem to contain audio. 

I am running nextcloud 25(.0.5) on an Ubuntu 20.04.6 installation.
The archive is built from tvheadend recordings which directly store mkv. To access the archive I am using kodi from different devices. But also vlc from my windows machine accessing the file using SMB does not show any audio stream.

Please tell me when I can help with additional information from my installation.
Informational topic: is there a way to influence the conversion like compression, selection auf audio streams etc?

May thanks!

**Comment by cwilby** [comment]
Hey @chriskloe,

I don't have a good answer for why ffmpeg isn't processing audio in this scenario unfortunately.

There is another ticket (https://github.com/cwilby/nextcloud-workflow-media-converter/issues/179) to add a textarea to store ffmpeg parameters to be passed during conversion.   

That may address this issue - stay tuned and thanks for the report 👍

**Comment by chriskloe** [comment]
Hi,

I hoped it would be related to an old ffmpeg version on my Ubuntu 20.04.
Today I upgraded to the latest LTS which is 22.04, now I'm on ffmpeg  4.4.2-0ubuntu0.22.04.1
I'm also on nextcloud 27.0.1.
But the problem is the same - no audio in the output. Maybe it's related to the input format as I understood mkv is just a container with a lot of possible input formats.
Would it help to provide sample files?

BR,
Christoph

**Comment by chriskloe** [comment]
ffprobe -i output about the file:
 Duration: 01:45:00.88, start: 0.000000, bitrate: 10192 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 336.740000
    Chapter #0:1: start 336.740000, end 5643.920000
    Chapter #0:2: start 5643.920000, end 6300.880000
  Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 1k tbn, 100 tbc (default)
  Stream #0:1(ger): Audio: mp2, 48000 Hz, stereo, s16p, 256 kb/s (default)
  Stream #0:2(mis): Audio: mp2, 48000 Hz, stereo, s16p, 256 kb/s (default)
  Stream #0:3(ger): Audio: ac3, 48000 Hz, stereo, fltp, 448 kb/s (default)
  Stream #0:4(ger): Subtitle: dvb_subtitle (default)
  Stream #0:5(qaa): Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s (default)

Let me guess - no idea which stream to use?

**Comment by cwilby** [comment]
@chriskloe - The plugin now offers more control over input/output options passed to ffmpeg.

You can use the [-map option](http://trac.ffmpeg.org/wiki/Map) ([full documentation](http://ffmpeg.org/ffmpeg.html#Advanced-options)) to select specific input streams and map them to your output.

**Comment by chriskloe** [comment]
Thanks but I can't test it due to  #409
