### ISSUE TITLE
Access to root `/` of filesystem required?

### ISSUE THREAD

**Issue by Sir-Photch** [cwilby/nextcloud-workflow-media-converter#368]
## Steps to reproduce
1. Enable open_basedir restriction
2. Enable workflow for videos, from `video/mp4` to `.av1`

### Expected behaviour
Conversion starts

### Actual behaviour
Conversion fails

Log error:

```
[PHP] Error: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (...) at /var/lib/nextcloud/apps/maps/vendor/symfony/process/Process.php#343

at 2023-07-23T13:14:15+00:00
```

```
[workflow_media_converter] Error: [Symfony\Component\Process\Exception\RuntimeException] :: (0) :: The provided cwd "/" does not exist. :: #0 /var/lib/nextcloud/apps/maps/vendor/symfony/process/Process.php(247): Symfony\Component\Process\Process->start()
#1 /var/lib/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(159): Symfony\Component\Process\Process->run()
#2 /var/lib/nextcloud/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(64): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->convertMedia()
#3 /usr/share/webapps/nextcloud/lib/public/BackgroundJob/Job.php(78): OCA\WorkflowMediaConverter\BackgroundJobs\ConvertMediaJob->run()
#4 /usr/share/webapps/nextcloud/lib/public/BackgroundJob/QueuedJob.php(57): OCP\BackgroundJob\Job->start()
#5 /usr/share/webapps/nextcloud/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\QueuedJob->start()
#6 /usr/share/webapps/nextcloud/cron.php(152): OCP\BackgroundJob\QueuedJob->execute()
#7 {main}

at 2023-07-23T13:14:15+00:00
```

Why does this workflow need access to root? Wouldn't it rather need something like `/usr/bin/ffmpeg`?

Or is this the issue because it tries to access a temporary working directory? Like here:
https://github.com/cwilby/nextcloud-workflow-media-converter/blob/36947f8387956d0cba3fb342a224d0cf8be8bbb9/lib/BackgroundJobs/ConvertMediaJob.php#L155
What is usually the value for `$tempOutputPath`? Would it be possible to manually set the directory for that?

**Comment by cwilby** [comment]
@Sir-Photch - Should be resolved by changing the `tempdirectory` option in Nextcloud configuration, as documented [here](https://docs.nextcloud.com/server/16/admin_manual/configuration_server/config_sample_php_parameters.html).

This plugin writes to the operating system's temporary directory, which I get from Nextcloud's SDK.  Changing that option should propagate to this plugin.
