### ISSUE TITLE
NC27 Compatibility

### ISSUE THREAD

**Issue by MadMakz** [cwilby/nextcloud-workflow-media-converter#376]
Pretty much copypasting #324 but for >=27

## Steps to reproduce
1. install nextcloud 27
 
 
 ### Expected behaviour
 
 App shouldn't be flagged as not compatibile
 ### Actual behaviour
 
 App is flagged as not compatibile

**Comment by sveken** [comment]
Now for NC28

**Comment by cwilby** [comment]
v1.9.0 released with support for 26 through 28
