### ISSUE TITLE
Feature request: allow passing options to ffmpeg

### ISSUE THREAD

**Issue by Cysioland** [cwilby/nextcloud-workflow-media-converter#397]
Currently we can set the output file, but what I'd like to have is the ability to pass some options to ffmpeg (eg. output codec, resolution, movflags)

**Comment by printplaatreparatie** [comment]
This would be really helpful for me, as I'm looking for a way to save space on my mp4 files.
With this feature, I would be able to use `-vcodec libx265 -crf 27` to dramatically reduce space without a noticeable quality drop.

**Comment by cwilby** [comment]
This is now supported in v1.9.0 in flow and batch conversion:

<img width="847" alt="image" src="https://github.com/cwilby/nextcloud-workflow-media-converter/assets/13686317/940ec958-ee21-4210-a768-564b41534b71">
