### ISSUE TITLE
Unable to install, version check fails

### ISSUE THREAD

**Issue by ruedigerkupper** [cwilby/nextcloud-workflow-media-converter#416]
## Steps to reproduce
1. Try to install the app .
2. Observe: "Server version 22 or lower is required."

### Expected behaviour
The app store lists v28 as the latest supported version. Installation should work.

### Actual behaviour
Cannot install: "Server version 22 or lower is required."

## Workflow Media Converter app

**Workflow Media Converter app version:** (see apps admin page: `/index.php/settings/apps`)

**Comment by cwilby** [comment]
This should now be resolved.  I was able to setup a new NC28 instance and install via the app store.

**Comment by moarsmokes** [comment]
Got the same issues.
![Screenshot 2024-04-18 223126](https://github.com/cwilby/nextcloud-workflow-media-converter/assets/24761507/00b4ac1e-e37a-4961-b468-68afee29a23c)
`## Server configuration detail

**Operating system:** Linux 6.1.79-Unraid #1 SMP PREEMPT_DYNAMIC Fri Mar 29 13:34:03 PDT 2024 x86_64

**Webserver:** nginx/1.24.0 (fpm-fcgi)

**Database:** mysql 10.11.6

**PHP version:** 8.3.6

Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, json, random, readline, Reflection, SPL, session, cgi-fcgi, bcmath, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, standard, intl, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, imap, SimpleXML, sockets, sodium, sqlite3, sysvsem, xml, xmlwriter, zip, exif, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, msgpack, igbinary, redis, memcached, imagick, mcrypt, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 28.0.4 - 28.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

[]
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.20.0
 - breezedark: 28.0.0
 - bruteforcesettings: 2.8.0
 - calendar: 4.6.7
 - camerarawpreviews: 0.8.4
 - circles: 28.0.0
 - cloud_federation_api: 1.11.0
 - cloud_py_api: 0.1.9
 - comments: 1.18.0
 - contacts: 5.5.3
 - contactsinteraction: 1.9.0
 - dashboard: 7.8.0
 - dav: 1.29.1
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_external: 1.20.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - fileslibreofficeedit: 1.1.0
 - firstrunwizard: 2.17.0
 - integration_paperless: 1.0.1
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - mediadc: 0.3.8
 - nextcloud_announcements: 1.17.0
 - notes: 4.9.4
 - notifications: 2.16.0
 - oauth2: 1.16.3
 - otpmanager: 0.5.3
 - password_policy: 1.18.0
 - passwords: 2024.4.21
 - photos: 2.4.0
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - richdocuments: 8.3.4
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - side_menu: 3.12.0
 - support: 1.11.1
 - survey_client: 1.16.0
 - systemtags: 1.18.0
 - tasks: 0.15.0
 - text: 3.9.1
 - theming: 2.3.0
 - twofactor_admin: 4.5.0
 - twofactor_backupcodes: 1.17.0
 - twofactor_nextcloud_notification: 3.9.0
 - twofactor_totp: 10.0.0-beta.2
 - twofactor_webauthn: 1.4.0
 - unroundedcorners: 1.1.2
 - updatenotification: 1.18.0
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - workflowengine: 2.10.0
Disabled:
 - admin_audit
 - duplicatefinder: 1.1.8
 - encryption: 2.16.0
 - imageconverter: 2.0.1
 - integration_onedrive: 3.2.1
 - suspicious_login
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.home.systemfehler.eu",
        "cloud.tail.systemfehler.eu"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.home.systemfehler.eu",
    "allow_local_remote_servers": true,
    "dbtype": "mysql",
    "version": "28.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [],
    "maintenance_window_start": 1,
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "memcache.local": "\\OC\\Memcache\\APCu",
    "upgrade.disable-web": true,
    "default_phone_region": "DE",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "pipe",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "maintenance": false,
    "loglevel": 2
}
```
</details>

**Cron Configuration:** Array
(
    [backgroundjobs_mode] => cron
    [lastcron] => 1713472205
)


**External storages:** yes

<details><summary>External storage configuration</summary>

```
No mounts configured
```
</details>

**Encryption:** no

**User-backends:** 
 * OC\User\Database


**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

`
