### ISSUE TITLE
Flow Tag Assigned Not Working

### ISSUE THREAD

**Issue by oguzcanking38** [cwilby/nextcloud-workflow-media-converter#418]
## Steps to reproduce
**1. Flow (Personal)
2. Creating New Flow With Tag Assigned (When section)
3. Assigning matched Tag to any video (and section)
4. Conversion not happening**

### Expected behaviour
**When tag assigned to a video has to convert**

### Actual behaviour
**When tag assigned to certain video nothing happens**

## Server configuration
NextCloud AIO Version 28 (Docker Setup) All Latest

**Operating system**: Ubuntu 22.04

Log:

{"reqId":"","level":3,"time":"2024-02-29T03:05:04+00:00","remoteAddr":"172.22.0.14","user":"oguzcanking38","app":"workflow_media_converter","method":"PUT","url":"/remote.php/dav/systemtags-relations/files/1547/1","message":"(0) :: OCA\\WorkflowMediaConverter\\Operation\\ConvertMediaOperation::handleEvent(): Argument #2 ($event) must be of type OCP\\EventDispatcher\\GenericEvent, OCP\\SystemTag\\MapperEvent given, called in /var/www/html/custom_apps/workflow_media_converter/lib/Operation/ConvertMediaOperation.php on line 58","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"workflow_media_converter","eventName":"OCP\\SystemTag\\ISystemTagObjectMapper::assignTags"},"id":"65dff521475c1"}

**Comment by cwilby** [comment]
@oguzcanking38 Fixed in 1.9.5 👍
