### ISSUE TITLE
cannot add conversion Batch

### ISSUE THREAD

**Issue by T-Lancer** [cwilby/nextcloud-workflow-media-converter#438]
## Steps to reproduce
1. setup a new batch convert
2. choose settings
3. save config

### Expected behaviour
I assume it should start converting

### Actual behaviour
Throws error message:

> Error saving
> 
> <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" translate="no" > <head data-requesttoken=""> <meta charset="utf-8"> <title> Nextcloud </title> <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0"> <meta name="apple-itunes-app" content="app-id=1125420102"> <meta name="theme-color" content="#0082c9"> <link rel="icon" href="/apps/theming/favicon?v=7c27daef"> <link rel="apple-touch-icon" href="/apps/theming/icon?v=7c27daef"> <link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9"> <link rel="manifest" href="/apps/theming/manifest?v=7c27daef" crossorigin="use-credentials"> <link rel="stylesheet" href="/apps/theming/css/default.css?v=70e2b24f-0"> <link rel="stylesheet" href="/core/css/guest.css?v=613143cc-0"> </head> <body id="body-login"> <noscript> <div id="nojavascript"> <div> This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page. </div> </div> </noscript> <input type="hidden" id="initial-state-core-versionHash" value="IjYxMzE0M2NjIg=="> <input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA="> <div class="wrapper"> <div class="v-align"> <header> <div id="header"> <div class="logo"></div> </div> </header> <main> <h1 class="hidden-visually"> Nextcloud </h1> <div class="guest-box"> <h2>Error</h2> <ul> <li> <p>404</p> <p class='hint'>The page could not be found on the server.</p> </li> </ul> </div> </main> </div> </div> <footer class="guest-box "> <p class="info"> <a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – a safe home for all your data </p> </footer> </body> </html>

## Workflow Media Converter app

**Workflow Media Converter app version: 1.10.3 with following fix https://github.com/cwilby/nextcloud-workflow-media-converter/issues/409#issuecomment-2047329487

## Server configuration
Nextcloud AIO Nextcloud AIO v8.1.0 in Docker on x86-64

## Browser
Firefox with uBlock and no script.  both disabled for nextcloud

Chrome with ublock, disabled

Javascript is enabled.

**Comment by Felix212** [comment]
I have the same problem. I figured out that there is a problem with path resolving. In my case the app is installed in /custom-apps. On the frontend the path correctly resolved. However the backend is listening on the default apps directory /apps. 
Thats why we get 404.
I dont have any experience in developing next cloud apps, but maybe [this](https://help.nextcloud.com/t/how-to-get-the-name-of-the-directory-where-the-app-is-installed/179389/9) forum post can help the devs

**Comment by AlexandruNegura** [comment]
Same problem here. So I have like all the problems opened currently on the issues page :))
So the App is not usable nor in Flow, nor by batch :(

**Comment by T-Lancer** [comment]
I can confirm conversion and UI works now. many thanks!
