### ISSUE TITLE
Make the extension not case sensitive

### ISSUE THREAD

**Issue by gui7545** [cwilby/nextcloud-workflow-media-converter#73]
Hello,

Great extension for Nextcloud, thanks for your development.
I have got a trouble with the case of the extension.
Some file have extension like ".mov", some other have the extension like ".MOV".
File with lowercase extension are fully recognise during the conversion process. 
File with uppercase extension are not recognise and not converted.
Is it possible to solve this issue ?
Thanks

**Comment by cwilby** [comment]
Hi @gui7545 

The workflow field is a regular expression, so you can use the 'I' flag to disable case sensitivity like so

/mov/i 

I have created an issue in the Nextcloud repo to add a file extension picker to the Flow editor to make this more user friendly.

Thanks,
Cameron

**Comment by cwilby** [comment]
https://github.com/nextcloud/server/issues/27591

**Comment by skruehoetl** [comment]
Aside from the workflow part of the application - could you maybe add case-insensitivity to the batch conversion option in the settings? That would be much appreciated... :-)

**Comment by cwilby** [comment]
Unfortunately I'm not sure I can, or, I think a better option is to be accurate / consistent with file extensions through some other process.

The API exposed by Nextcloud (that I'm using [here](https://github.com/cwilby/nextcloud-workflow-media-converter/blob/32533fec2541b4bf8284a33ab88817ea7d5b26bb/lib/BackgroundJobs/BatchConvertMediaJob.php#L107)) doesn't give me any options to override case sensitivity, and I can understand why given how case sensitivity is managed across the different operating systems Nextcloud can run on.
